from module.atom.image import RuleImage
from module.atom.click import RuleClick
from module.atom.long_click import RuleLongClick
from module.atom.swipe import RuleSwipe
from module.atom.ocr import RuleOcr
from module.atom.list import RuleList

# This file was automatically generated by ./dev_tools/assets_extract.py.
# Don't modify it manually.
class PeriodicActivityAssets: 


	# Image Rule Assets
	# 从庭院进入灵染试炼活动 
	I_FP_ACCESS = RuleImage(roi_front=(1192,317,36,34), roi_back=(1000,101,261,472), threshold=0.8, method="Template matching", file="./tasks/PeriodicActivity/fp/fp_fp_access.png")
	# 寻找切换按钮 
	I_TOGGLE_BUTTON = RuleImage(roi_front=(1202,466,22,21), roi_back=(1090,127,176,377), threshold=0.7, method="Template matching", file="./tasks/PeriodicActivity/fp/fp_toggle_button.png")
	# 进入灵染试炼战斗界面 
	I_FP_ACCESS_1 = RuleImage(roi_front=(264,339,26,95), roi_back=(129,202,329,380), threshold=0.7, method="Template matching", file="./tasks/PeriodicActivity/fp/fp_fp_access_1.png")
	# 挑战 
	I_FP_CHALLENGE = RuleImage(roi_front=(1159,598,60,29), roi_back=(1159,598,60,29), threshold=0.8, method="Template matching", file="./tasks/PeriodicActivity/fp/fp_fp_challenge.png")
	# description 
	I_BATTLE_SUCCESS = RuleImage(roi_front=(435,147,100,100), roi_back=(435,147,100,100), threshold=0.8, method="Template matching", file="./tasks/PeriodicActivity/fp/battle_success.png")
	# 关闭获取皮肤弹窗 
	I_FP_CLOSE_GET_SKIN = RuleImage(roi_front=(932,227,43,43), roi_back=(887,59,317,243), threshold=0.8, method="Template matching", file="./tasks/PeriodicActivity/fp/fp_fp_close_get_skin.png")


	# Ocr Rule Assets
	# 战斗次数 
	O_BATTLE_NUM = RuleOcr(roi=(1144,408,100,21), area=(1144,408,100,21), mode="DigitCounter", method="Default", keyword="", name="battle_num")


	# Click Rule Assets
	#  
	C_GAS_REWARD_1 = RuleClick(roi_front=(658,579,57,55), roi_back=(658,579,57,55), name="gas_reward_1")
	#  
	C_GAS_REWARD_2 = RuleClick(roi_front=(753,580,57,55), roi_back=(753,580,57,55), name="gas_reward_2")
	#  
	C_GAS_REWARD_3 = RuleClick(roi_front=(850,577,57,55), roi_back=(850,577,57,55), name="gas_reward_3")
	#  
	C_GAS_REWARD_4 = RuleClick(roi_front=(945,580,57,55), roi_back=(945,580,57,55), name="gas_reward_4")
	#  
	C_GAS_REWARD_5 = RuleClick(roi_front=(1041,578,57,55), roi_back=(1041,578,57,55), name="gas_reward_5")


	# Image Rule Assets
	# 呱呱画室主页面 
	I_CHECK_GUGU_ACT = RuleImage(roi_front=(1069,20,33,40), roi_back=(1052,10,74,59), threshold=0.7, method="Template matching", file="./tasks/PeriodicActivity/gas/gas_check_gugu_act.png")
	# 获取颜料 
	I_OBTAIN_PAINT = RuleImage(roi_front=(1156,453,51,55), roi_back=(1118,406,156,149), threshold=0.7, method="Template matching", file="./tasks/PeriodicActivity/gas/gas_obtain_paint.png")
	# 提交颜料 
	I_SUBMIT_PAINT = RuleImage(roi_front=(1151,590,58,76), roi_back=(1117,552,148,151), threshold=0.8, method="Template matching", file="./tasks/PeriodicActivity/gas/gas_submit_paint.png")
	# 可以挑战标志 
	I_GAS_CAN_FIRE = RuleImage(roi_front=(1106,578,92,96), roi_back=(1077,548,157,158), threshold=0.8, method="Template matching", file="./tasks/PeriodicActivity/gas/gas_gas_can_fire.png")
	# 前往提交 
	I_GOTO_SUBMIT = RuleImage(roi_front=(694,401,124,62), roi_back=(672,386,165,91), threshold=0.8, method="Template matching", file="./tasks/PeriodicActivity/gas/gas_goto_submit.png")
	# 前往获取 
	I_GOTO_OBTAIN = RuleImage(roi_front=(696,400,126,63), roi_back=(688,391,141,85), threshold=0.8, method="Template matching", file="./tasks/PeriodicActivity/gas/gas_goto_obtain.png")
	# 不能挑战标志 
	I_GAS_CANNOT_FIRE = RuleImage(roi_front=(1100,577,100,100), roi_back=(1078,563,142,128), threshold=0.8, method="Template matching", file="./tasks/PeriodicActivity/gas/gas_gas_cannot_fire.png")
	# 庭院前往呱呱画室按钮 
	I_GAS_MAIN_TO_GUGU = RuleImage(roi_front=(1183,381,44,32), roi_back=(1167,108,81,475), threshold=0.8, method="Template matching", file="./tasks/PeriodicActivity/gas/gas_gas_main_to_gugu.png")
	# 奖励已领取 
	I_GAS_ALREADY_GET_REWARD = RuleImage(roi_front=(666,599,39,15), roi_back=(517,536,594,125), threshold=0.8, method="Template matching", file="./tasks/PeriodicActivity/gas/gas_gas_already_get_reward.png")
	# 奖励锁定中不能领取 
	I_GAS_REWARD_LOCK = RuleImage(roi_front=(790,582,14,15), roi_back=(517,536,594,125), threshold=0.8, method="Template matching", file="./tasks/PeriodicActivity/gas/gas_gas_reward_lock.png")
	# 解锁阵容状态 
	I_GAS_UNLOCK = RuleImage(roi_front=(885,659,16,21), roi_back=(845,637,224,79), threshold=0.8, method="Template matching", file="./tasks/PeriodicActivity/gas/gas_gas_unlock.png")
	# 锁定阵容状态 
	I_GAS_LOCK = RuleImage(roi_front=(885,659,16,21), roi_back=(845,637,224,79), threshold=0.8, method="Template matching", file="./tasks/PeriodicActivity/gas/gas_gas_lock.png")


	# Click Rule Assets
	# description 
	C_ANSWER_ENSURE_1 = RuleClick(roi_front=(1219,185,21,34), roi_back=(1218,184,23,37), name="answer_ensure_1")
	# description 
	C_ANSWER_ENSURE_2 = RuleClick(roi_front=(1223,298,19,26), roi_back=(1222,297,22,29), name="answer_ensure_2")
	# description 
	C_ANSWER_ENSURE_3 = RuleClick(roi_front=(1224,414,18,23), roi_back=(1223,413,21,26), name="answer_ensure_3")
	# description 
	C_ANSWER_ENSURE_4 = RuleClick(roi_front=(1226,524,13,29), roi_back=(1224,523,15,31), name="answer_ensure_4")


	# Image Rule Assets
	# description 
	I_ENTRY = RuleImage(roi_front=(770,373,33,139), roi_back=(745,281,142,329), threshold=0.8, method="Template matching", file="./tasks/PeriodicActivity/quiz/entry.png")
	# 开始 
	I_START = RuleImage(roi_front=(1149,608,66,41), roi_back=(1136,574,100,100), threshold=0.8, method="Template matching", file="./tasks/PeriodicActivity/quiz/quiz_start.png")
	# 标志 
	I_MESSAGE = RuleImage(roi_front=(73,483,53,46), roi_back=(51,450,170,136), threshold=0.8, method="Template matching", file="./tasks/PeriodicActivity/quiz/message.png")
	# 失败然后离开 
	I_FAIL_QUIT = RuleImage(roi_front=(612,534,67,31), roi_back=(375,484,524,163), threshold=0.8, method="Template matching", file="./tasks/PeriodicActivity/quiz/fail_quit.png")
	# 结算分享 
	I_SHARE = RuleImage(roi_front=(1171,625,53,44), roi_back=(1152,592,100,100), threshold=0.8, method="Template matching", file="./tasks/PeriodicActivity/quiz/quiz_share.png")
	# description 
	I_ALONE_ENSURE = RuleImage(roi_front=(1216,405,30,41), roi_back=(1138,148,140,435), threshold=0.7, method="Template matching", file="./tasks/PeriodicActivity/quiz/alone_ensure.png")


	# Ocr Rule Assets
	# Ocr-description 
	O_QUESTION = RuleOcr(roi=(903,32,322,101), area=(0,0,100,100), mode="Full", method="Default", keyword="", name="question")
	# Ocr-description 
	O_ANSWER1 = RuleOcr(roi=(951,188,228,31), area=(949,187,231,34), mode="Single", method="Default", keyword="", name="answer1")
	# Ocr-description 
	O_ANSWER2 = RuleOcr(roi=(960,301,208,26), area=(959,300,211,29), mode="Single", method="Default", keyword="", name="answer2")
	# Ocr-description 
	O_ANSWER3 = RuleOcr(roi=(955,417,228,26), area=(953,415,231,29), mode="Single", method="Default", keyword="", name="answer3")
	# Ocr-description 
	O_ANSWER4 = RuleOcr(roi=(964,527,208,23), area=(963,526,211,26), mode="Single", method="Default", keyword="", name="answer4")
	# 倒计时 
	O_COUNTDOWN = RuleOcr(roi=(1030,9,61,25), area=(1029,7,63,27), mode="Digit", method="Default", keyword="4", name="countdown")
	# 倒计时 
	O_COUNTDOWN3 = RuleOcr(roi=(1045,6,27,30), area=(1045,6,27,30), mode="Digit", method="Default", keyword="3", name="countdown3")
	# Ocr-description 
	O_QUESTION_AND_ANSWER = RuleOcr(roi=(902,34,325,534), area=(0,0,100,100), mode="Full", method="Default", keyword="", name="question_and_answer")


