from module.atom.image import RuleImage
from module.atom.click import RuleClick
from module.atom.long_click import RuleLongClick
from module.atom.swipe import RuleSwipe
from module.atom.ocr import RuleOcr
from module.atom.list import RuleList

# This file was automatically generated by ./dev_tools/assets_extract.py.
# Don't modify it manually.
class DraftDuelAssets: 


	# Click Rule Assets
	# 选人界面左侧候选 
	C_DRAFT_LEFT_SELECT = RuleClick(roi_front=(350,625,95,75), roi_back=(350,625,95,75), name="draft_left_select")
	# 选人界面中间候选 
	C_DRAFT_MIDDLE_SELECT = RuleClick(roi_front=(720,625,95,75), roi_back=(720,625,95,75), name="draft_middle_select")
	# 选人界面右侧候选 
	C_DRAFT_RIGHT_SELECT = RuleClick(roi_front=(1090,625,95,75), roi_back=(1090,625,95,75), name="draft_right_select")
	# 阵容详情第1张卡 
	C_BATTLE_DETAIL_0 = RuleClick(roi_front=(95,46,40,42), roi_back=(95,46,40,42), name="battle_detail_0")
	# 阵容详情第2张卡 
	C_BATTLE_DETAIL_1 = RuleClick(roi_front=(170,46,40,42), roi_back=(170,46,40,42), name="battle_detail_1")
	# 阵容详情第3张卡 
	C_BATTLE_DETAIL_2 = RuleClick(roi_front=(245,46,40,42), roi_back=(245,46,40,42), name="battle_detail_2")
	# 阵容详情第4张卡 
	C_BATTLE_DETAIL_3 = RuleClick(roi_front=(315,46,40,42), roi_back=(315,46,40,42), name="battle_detail_3")
	# 阵容详情第5张卡 
	C_BATTLE_DETAIL_4 = RuleClick(roi_front=(385,46,40,42), roi_back=(385,46,40,42), name="battle_detail_4")
	# 阵容详情第6张卡 
	C_BATTLE_DETAIL_5 = RuleClick(roi_front=(460,46,40,42), roi_back=(460,46,40,42), name="battle_detail_5")
	# 阵容详情“我的”页签 
	C_DETAIL_MINE = RuleClick(roi_front=(1090,642,60,60), roi_back=(1090,642,60,60), name="detail_mine")
	# 关闭阵容详情 
	C_DETAIL_CLOSE = RuleClick(roi_front=(1170,93,60,60), roi_back=(1170,93,60,60), name="detail_close")
	# 确认上场 
	C_BATTLE_CONFIRM = RuleClick(roi_front=(1120,565,100,100), roi_back=(1120,565,100,100), name="battle_confirm")
	# 拒绝悬赏弹窗 
	C_BOUNTY_REJECT = RuleClick(roi_front=(818,485,80,72), roi_back=(818,485,80,72), name="bounty_reject")
	# 好友邀请取消 
	C_FRIEND_CANCEL = RuleClick(roi_front=(479,443,95,49), roi_back=(479,443,95,49), name="friend_cancel")
	# 结算点击继续 
	C_RESULT_CONTINUE = RuleClick(roi_front=(605,662,75,54), roi_back=(605,662,75,54), name="result_continue")


	# Image Rule Assets
	# 大厅“战”按钮 
	I_DRAFT_START = RuleImage(roi_front=(1169,591,65,67), roi_back=(1169,591,65,67), threshold=0.8, method="Template matching", file="./tasks/DraftDuel/res/draft_start.png")
	# 组队模式下队友位为空 
	I_EMPTY_TEAMMATE = RuleImage(roi_front=(983,330,62,56), roi_back=(983,330,62,56), threshold=0.83, method="Template matching", file="./tasks/DraftDuel/res/empty_teammate.png")


	# Ocr Rule Assets
	# 第N名式神提示 
	O_DRAFT_ROUND = RuleOcr(roi=(450,120,380,55), area=(450,120,380,55), mode="Single", method="Default", keyword="", name="draft_round")
	# 左侧候选式神名 
	O_DRAFT_LEFT_NAME = RuleOcr(roi=(190,652,150,55), area=(190,652,150,55), mode="Single", method="Default", keyword="", name="draft_left_name")
	# 中间候选式神名 
	O_DRAFT_MIDDLE_NAME = RuleOcr(roi=(555,652,180,55), area=(555,652,180,55), mode="Single", method="Default", keyword="", name="draft_middle_name")
	# 右侧候选式神名 
	O_DRAFT_RIGHT_NAME = RuleOcr(roi=(970,652,150,55), area=(970,652,150,55), mode="Single", method="Default", keyword="", name="draft_right_name")
	# 上场确认按钮文字 
	O_BATTLE_CONFIRM = RuleOcr(roi=(1060,540,210,110), area=(1060,540,210,110), mode="Single", method="Default", keyword="", name="battle_confirm")
	# 阵容详情标题 
	O_DETAIL_TITLE = RuleOcr(roi=(535,20,210,50), area=(535,20,210,50), mode="Single", method="Default", keyword="", name="detail_title")
	# 阵容详情第1位式神名 
	O_LINEUP_NAME_0 = RuleOcr(roi=(230,151,190,50), area=(230,151,190,50), mode="Single", method="Default", keyword="", name="lineup_name_0")
	# 阵容详情第2位式神名 
	O_LINEUP_NAME_1 = RuleOcr(roi=(420,151,190,50), area=(420,151,190,50), mode="Single", method="Default", keyword="", name="lineup_name_1")
	# 阵容详情第3位式神名 
	O_LINEUP_NAME_2 = RuleOcr(roi=(615,151,190,50), area=(615,151,190,50), mode="Single", method="Default", keyword="", name="lineup_name_2")
	# 阵容详情第4位式神名 
	O_LINEUP_NAME_3 = RuleOcr(roi=(805,151,190,50), area=(805,151,190,50), mode="Single", method="Default", keyword="", name="lineup_name_3")
	# 阵容详情第5位式神名 
	O_LINEUP_NAME_4 = RuleOcr(roi=(995,151,190,50), area=(995,151,190,50), mode="Single", method="Default", keyword="", name="lineup_name_4")
	# 阵容详情第1位速度 
	O_LINEUP_SPEED_0 = RuleOcr(roi=(278,346,85,31), area=(278,346,85,31), mode="Single", method="Default", keyword="", name="lineup_speed_0")
	# 阵容详情第2位速度 
	O_LINEUP_SPEED_1 = RuleOcr(roi=(468,346,85,31), area=(468,346,85,31), mode="Single", method="Default", keyword="", name="lineup_speed_1")
	# 阵容详情第3位速度 
	O_LINEUP_SPEED_2 = RuleOcr(roi=(663,346,85,31), area=(663,346,85,31), mode="Single", method="Default", keyword="", name="lineup_speed_2")
	# 阵容详情第4位速度 
	O_LINEUP_SPEED_3 = RuleOcr(roi=(853,346,85,31), area=(853,346,85,31), mode="Single", method="Default", keyword="", name="lineup_speed_3")
	# 阵容详情第5位速度 
	O_LINEUP_SPEED_4 = RuleOcr(roi=(1043,346,85,31), area=(1043,346,85,31), mode="Single", method="Default", keyword="", name="lineup_speed_4")
	# 阵容详情第1位防御 
	O_LINEUP_DEFENSE_0 = RuleOcr(roi=(278,303,85,31), area=(278,303,85,31), mode="Single", method="Default", keyword="", name="lineup_defense_0")
	# 阵容详情第2位防御 
	O_LINEUP_DEFENSE_1 = RuleOcr(roi=(468,303,85,31), area=(468,303,85,31), mode="Single", method="Default", keyword="", name="lineup_defense_1")
	# 阵容详情第3位防御 
	O_LINEUP_DEFENSE_2 = RuleOcr(roi=(663,303,85,31), area=(663,303,85,31), mode="Single", method="Default", keyword="", name="lineup_defense_2")
	# 阵容详情第4位防御 
	O_LINEUP_DEFENSE_3 = RuleOcr(roi=(853,303,85,31), area=(853,303,85,31), mode="Single", method="Default", keyword="", name="lineup_defense_3")
	# 阵容详情第5位防御 
	O_LINEUP_DEFENSE_4 = RuleOcr(roi=(1043,303,85,31), area=(1043,303,85,31), mode="Single", method="Default", keyword="", name="lineup_defense_4")
	# 大厅番胜数 
	O_LOBBY_SCORE = RuleOcr(roi=(98,81,240,123), area=(98,81,240,123), mode="Single", method="Default", keyword="", name="lobby_score")
	# 点击屏幕继续 
	O_RESULT_CONTINUE = RuleOcr(roi=(492,657,290,55), area=(492,657,290,55), mode="Single", method="Default", keyword="", name="result_continue")
	# 终局结算文本 
	O_TERMINAL_RESULT = RuleOcr(roi=(460,140,380,190), area=(460,140,380,190), mode="Single", method="Default", keyword="", name="terminal_result")
	# 悬赏拒绝弹窗文字 
	O_BOUNTY_REJECT = RuleOcr(roi=(885,477,120,83), area=(885,477,120,83), mode="Single", method="Default", keyword="", name="bounty_reject")
	# 好友邀请取消文字 
	O_FRIEND_CANCEL = RuleOcr(roi=(435,434,165,65), area=(435,434,165,65), mode="Single", method="Default", keyword="", name="friend_cancel")


