from module.atom.image import RuleImage
from module.atom.click import RuleClick
from module.atom.long_click import RuleLongClick
from module.atom.swipe import RuleSwipe
from module.atom.ocr import RuleOcr
from module.atom.list import RuleList

# This file was automatically generated by ./dev_tools/assets_extract.py.
# Don't modify it manually.
class LBSAssets: 


	# Image Rule Assets
	# 前往LBS活动 
	I_MAIN_GOTO_LBS = RuleImage(roi_front=(1182,453,50,31), roi_back=(1170,117,83,400), threshold=0.8, method="Template matching", file="./tasks/LBS/lbs/lbs_main_goto_lbs.png")
	# LBS活动页面标志 
	I_CHECK_LBS = RuleImage(roi_front=(201,227,47,34), roi_back=(201,227,47,34), threshold=0.8, method="Template matching", file="./tasks/LBS/lbs/lbs_check_lbs.png")
	# LBS商店标志 
	I_CHECK_LBS_SHOP = RuleImage(roi_front=(669,85,101,29), roi_back=(669,85,101,29), threshold=0.8, method="Template matching", file="./tasks/LBS/lbs/lbs_check_lbs_shop.png")
	# 活动前往商店页面 
	I_ACTIVITY_GOTO_SHOP = RuleImage(roi_front=(104,292,62,91), roi_back=(104,292,62,91), threshold=0.8, method="Template matching", file="./tasks/LBS/lbs/lbs_activity_goto_shop.png")
	# 商店前往活动页面 
	I_SHOP_GOTO_ACTIVITY = RuleImage(roi_front=(103,155,62,91), roi_back=(103,155,62,91), threshold=0.8, method="Template matching", file="./tasks/LBS/lbs/lbs_shop_goto_activity.png")
	# 现世祝福 
	I_LBS_BLESSING = RuleImage(roi_front=(489,157,95,31), roi_back=(184,126,983,520), threshold=0.8, method="Template matching", file="./tasks/LBS/lbs/lbs_lbs_blessing.png")
	# 地图页稳定特征 
	I_CHECK_LBS_MAP = RuleImage(roi_front=(28,614,55,51), roi_back=(28,614,55,51), threshold=0.8, method="Template matching", file="./tasks/LBS/lbs/lbs_check_lbs_map.png")
	# 右下角活动图标 
	I_MAP_GOTO_ACTIVITY = RuleImage(roi_front=(1128,565,55,51), roi_back=(1128,565,55,51), threshold=0.8, method="Template matching", file="./tasks/LBS/lbs/lbs_map_goto_activity.png")


	# Image Rule Assets
	# 刷新 
	I_REFRESH = RuleImage(roi_front=(1189,525,36,32), roi_back=(1178,129,65,434), threshold=0.8, method="Template matching", file="./tasks/LBS/res/res_refresh.png")
	# 活动入口 
	I_ACTIVITY_ENTRY = RuleImage(roi_front=(1168,127,77,449), roi_back=(1168,127,78,449), threshold=0.8, method="Template matching", file="./tasks/LBS/res/res_activity_entry.png")
	# 组队 
	I_TEAM_UP = RuleImage(roi_front=(1119,577,61,35), roi_back=(1117,574,70,73), threshold=0.8, method="Template matching", file="./tasks/LBS/res/res_team_up.png")
	# 创建（点组队后出现，点它进标准组队界面） 
	I_TEAM_CREATE = RuleImage(roi_front=(598,493,79,35), roi_back=(598,493,79,35), threshold=0.8, method="Template matching", file="./tasks/LBS/res/res_team_create.png")
	# 挑战 
	I_CHALLENGE = RuleImage(roi_front=(1196,617,54,45), roi_back=(1196,617,54,45), threshold=0.8, method="Template matching", file="./tasks/LBS/res/res_challenge.png")


	# Ocr Rule Assets
	# 剩余挑战次数 
	O_REMAIN_COUNT = RuleOcr(roi=(1089,680,37,27), area=(1091,680,33,27), mode="Digit", method="Default", keyword="", name="remain_count")


