from module.atom.image import RuleImage
from module.atom.click import RuleClick
from module.atom.long_click import RuleLongClick
from module.atom.swipe import RuleSwipe
from module.atom.ocr import RuleOcr
from module.atom.list import RuleList

# This file was automatically generated by ./dev_tools/assets_extract.py.
# Don't modify it manually.
class LBSAssets: 


	# Image Rule Assets
	# 刷新 
	I_REFRESH = RuleImage(roi_front=(1189,525,36,32), roi_back=(1178,129,65,434), threshold=0.8, method="Template matching", file="./tasks/LBS/res/res_refresh.png")
	# 活动入口 
	I_ACTIVITY_ENTRY = RuleImage(roi_front=(1168,127,77,449), roi_back=(1168,127,78,449), threshold=0.8, method="Template matching", file="./tasks/LBS/res/res_activity_entry.png")
	# 组队 
	I_TEAM_UP = RuleImage(roi_front=(1119,577,61,35), roi_back=(1117,574,70,73), threshold=0.8, method="Template matching", file="./tasks/LBS/res/res_team_up.png")
	# 创建（点组队后出现，点它进标准组队界面） 
	I_TEAM_CREATE = RuleImage(roi_front=(598,493,79,35), roi_back=(598,493,79,35), threshold=0.8, method="Template matching", file="./tasks/LBS/res/res_team_create.png")
	# 挑战 
	I_CHALLENGE = RuleImage(roi_front=(1196,617,54,45), roi_back=(1196,617,54,45), threshold=0.8, method="Template matching", file="./tasks/LBS/res/res_challenge.png")


	# Ocr Rule Assets
	# 剩余挑战次数 
	O_REMAIN_COUNT = RuleOcr(roi=(1089,680,37,27), area=(1091,680,33,27), mode="Digit", method="Default", keyword="", name="remain_count")


