from module.atom.image import RuleImage
from module.atom.click import RuleClick
from module.atom.long_click import RuleLongClick
from module.atom.swipe import RuleSwipe
from module.atom.ocr import RuleOcr
from module.atom.list import RuleList

# This file was automatically generated by ./dev_tools/assets_extract.py.
# Don't modify it manually.
class VersionActivityAssets: 


	# Image Rule Assets
	# moon_entry 
	I_MOON_ENTRY = RuleImage(roi_front=(1180,289,54,59), roi_back=(1115,100,165,490), threshold=0.8, method="Template matching", file="./tasks/VersionActivity/as/moonlight/moon_entry.png")
	# moon_lobby 
	I_MOON_LOBBY = RuleImage(roi_front=(151,23,130,31), roi_back=(125,10,185,65), threshold=0.8, method="Template matching", file="./tasks/VersionActivity/as/moonlight/moon_lobby.png")
	# moon_enter_battle 
	I_MOON_ENTER_BATTLE = RuleImage(roi_front=(470,110,31,119), roi_back=(435,70,110,215), threshold=0.8, method="Template matching", file="./tasks/VersionActivity/as/moonlight/moon_enter_battle.png")
	# moon_battle 
	I_MOON_BATTLE = RuleImage(roi_front=(158,30,120,28), roi_back=(125,10,190,70), threshold=0.8, method="Template matching", file="./tasks/VersionActivity/as/moonlight/moon_battle.png")
	# moon_challenge 
	I_MOON_CHALLENGE = RuleImage(roi_front=(1144,609,76,34), roi_back=(1100,568,165,132), threshold=0.8, method="Template matching", file="./tasks/VersionActivity/as/moonlight/moon_challenge.png")


	# Ocr Rule Assets
	# 月华流光挑战资源数量 
	O_MOON_RESOURCE = RuleOcr(roi=(1110,24,102,39), area=(1110,24,102,39), mode="Digit", method="Default", keyword="", name="moon_resource")
	# 月华流光奖励已达上限的提示文本 
	O_MOON_REWARD_NOTICE = RuleOcr(roi=(410,255,445,78), area=(410,255,445,78), mode="Full", method="Default", keyword="", name="moon_reward_notice")


