from module.atom.image import RuleImage
from module.atom.click import RuleClick
from module.atom.long_click import RuleLongClick
from module.atom.swipe import RuleSwipe
from module.atom.ocr import RuleOcr
from module.atom.list import RuleList

# This file was automatically generated by ./dev_tools/assets_extract.py.
# Don't modify it manually.
class StoryLineAssets: 


	# Click Rule Assets
	# 随机点击推进对话区域 
	C_STORY_DIALOG_TAP = RuleClick(roi_front=(500,280,280,200), roi_back=(500,280,280,200), name="story_dialog_tap")


	# Image Rule Assets
	# 剧情对话三点 
	I_STORY_DIALOG_DOTS = RuleImage(roi_front=(839,243,43,14), roi_back=(0,102,1277,618), threshold=0.85, method="Template matching", file="./tasks/StoryLine/res/story_dialog_dots.png")
	# 剧情问号徽章 
	I_STORY_DIALOG_QUESTION = RuleImage(roi_front=(1129,267,23,26), roi_back=(0,102,1280,618), threshold=0.8, method="Multi-scale template matching", file="./tasks/StoryLine/res/story_dialog_question.png")
	# 剧情对话眼睛按钮 
	I_STORY_DIALOG_EYE = RuleImage(roi_front=(628,166,22,28), roi_back=(0,0,1280,720), threshold=0.85, method="Template matching", file="./tasks/StoryLine/res/story_dialog_eye.png")
	# 右上跳过按钮 
	I_STORY_SKIP_RIGHT = RuleImage(roi_front=(1192,40,44,39), roi_back=(900,0,380,200), threshold=0.8, method="Template matching", file="./tasks/StoryLine/res/story_skip_button.png")
	# 剧情结束终字(模板) 
	I_STORY_END = RuleImage(roi_front=(604,260,77,15), roi_back=(598,252,87,203), threshold=0.8, method="Template matching", file="./tasks/StoryLine/res/story_end.png")
	# 庭院自动弹窗取消按钮(模板) 
	I_STORY_POPUP_CANCEL = RuleImage(roi_front=(1146,70,49,48), roi_back=(556,43,722,277), threshold=0.8, method="Template matching", file="./tasks/StoryLine/res/story_popup_cancel.png")


	# Ocr Rule Assets
	# 底部跳过文字 
	O_STORY_SKIP = RuleOcr(roi=(832,553,75,35), area=(821,548,99,45), mode="Single", method="Default", keyword="跳过", name="story_skip")
	# 确认跳过文字 
	O_STORY_CONFIRM_SKIP = RuleOcr(roi=(715,443,136,36), area=(686,425,185,71), mode="Single", method="Default", keyword="确认跳过", name="story_confirm_skip")
	# 等级要求 lv.xx 判定 
	O_STORY_LEVEL = RuleOcr(roi=(822,253,71,35), area=(812,232,100,79), mode="Full", method="Default", keyword="Lv", name="story_level")


